from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

START_MARKER = "<!-- VAULTWARES_AGENTCIATION:MANAGED:START -->"
END_MARKER = "<!-- VAULTWARES_AGENTCIATION:MANAGED:END -->"

MANAGED_BLOCK = """<!-- VAULTWARES_AGENTCIATION:MANAGED:START -->
<!--
   This block is generated by `vault-themes/theme-manager/tools/sync_submodule_rules.py`.
   Do not edit by hand. Edit `vault-themes/brand/ui-kit.md` and re-run the sync tool.
   Last updated: May 17, 2026
-->

# VaultWares — Agent Quick Brief

You are operating inside a **VaultWares** repository. Before any UI, branding, theme, design-token, or user-facing string change, **read the canonical sources** in this order:

1. `vault-themes/AGENTS.md` — top rules, security posture, theme catalogue.
2. `vault-themes/brand/ui-kit.md` — **product-UI vocabulary** (this is the most important one for any UI task).
3. `vault-themes/brand/brand-guide.md` — voice + brand foundation.
4. `vault-themes/brand/tokens/tokens.ts` — live token values.
5. `vault-themes/brand/i18n/brand.i18n.ts` — canonical EN/FR strings.

If the `vault-themes` submodule isn't checked out in this repo, fetch it before proceeding. If it cannot be fetched, ask the user before making any visual decision.

## Non-negotiables

- **VaultWares products are instruments, not websites.** Default to: app shell · sidebar · list with hairline dividers · right-rail drawers · status bar. *Not*: card grids, hero panels, marketing CTAs, bubble pills.
- **Tokens, not hex.** All colors, spacing, fonts, radii, motion, and glass values come from `vault.*` tokens. Never hardcode.
- **Bilingual parity.** Every visible string has both `en` and `fr` (Quebec French). FR runs +15–20% longer — layouts must tolerate it.
- **No emoji in product/UI/marketing copy.** No unicode glyphs as icons. Use Lucide.
- **No glass on full pages.** Glass is reserved for command palettes and rare focused overlays.
- **No fear copy.** Forbidden: "military-grade", "hacker-proof", "bulletproof", "Proceed", "CRITICAL SECURITY WARNING", "just", "simply", "easy" (unless factually proven). Replace with calm, technically honest language.
- **Privacy first.** Never design a flow where the server can read, persist, derive, or reconstruct private keys or shared decryption keys used between two clients. ML-KEM is the post-quantum KEM target.
- **Accessibility.** Body contrast ≥ 4.5:1 (WCAG AA). Large/UI ≥ 3.0:1. Focus visible in both modes. State never relies on color alone.

## Color quick reference

| Token | Hex | Role |
| --- | --- | --- |
| `vault.gold` | `#CC9B21` | **Brand accent** — V mark, primary actions only |
| `vault.cyan` | `#21B8CC` | **Interaction** — focus, links, radio "selected" |
| `vault.green` | `#4ECC21` | Secured / success / "live" toggles |
| `vault.burgundy` | `#A63D40` | Error / destructive |
| `vault.base` | `#002B36` | Dark surface (NOT black) |
| `vault.paper` | `#FDF6E3` | Light surface (NOT white) |

Gold = brand. Cyan = interaction. Green = secured. Burgundy = destructive. **They never swap roles.**

## Voice anchors

- Tagline: *"Privacy first. Security in service."* / *"La confidentialité d'abord. La sécurité au service."*
- Replace *"Encrypted with military-grade AES-256"* → *"Vault secured."*
- Replace *"Critical security warning"* → *"We noticed something. Here's what to do."*
- Replace *"Proceed"* → *"Continue."*

## Anti-patterns to reject on sight

Pure black backgrounds · neon green · Matrix rain · padlock illustrations · multi-stop gradients · backdrop-filter on full pages · emoji as icons · cards with gradient backgrounds or left-accent stripes · "AI-coded" rainbow chrome · infinite decorative motion loops · hardcoded hex outside `tokens.ts` · EN strings without FR counterparts.

## When in doubt

Ask the user. Cite the source file you read. Do not invent values, do not guess colors, do not synthesize French translations — read `brand.i18n.ts` or ask.

<!-- VAULTWARES_AGENTCIATION:MANAGED:END -->
"""

@dataclass(frozen=True)
class Target:
    name: str
    relative_path: Path
    block: str
    empty_prefix: str = ""

TARGETS = {
    "codex": Target("codex", Path("AGENTS.md"), MANAGED_BLOCK),
    "claude": Target("claude", Path("CLAUDE.md"), MANAGED_BLOCK),
    "copilot": Target("copilot", Path(".github/copilot-instructions.md"), MANAGED_BLOCK),
    "cursor": Target("cursor", Path(".cursor/rules/vaultwares.mdc"), MANAGED_BLOCK),
    "cursorrules": Target("cursorrules", Path(".cursorrules"), MANAGED_BLOCK),
    "windsurf": Target("windsurf", Path(".windsurf/rules/vaultwares.md"), MANAGED_BLOCK),
    "windsurfrules": Target("windsurfrules", Path(".windsurfrules"), MANAGED_BLOCK),
    "continue": Target("continue", Path(".continue/rules/vaultwares.md"), MANAGED_BLOCK),
    "vscode": Target("vscode", Path(".vscode/vault-themes.instructions.md"), MANAGED_BLOCK),
    "cli": Target("cli", Path("CONTEXT.md"), MANAGED_BLOCK),
    "tui": Target("tui", Path("TUI_AGENTS.md"), MANAGED_BLOCK),
    "aider": Target("aider", Path("CONVENTIONS.md"), MANAGED_BLOCK),
    "gemini": Target("gemini", Path("GEMINI.md"), MANAGED_BLOCK),
    "zed": Target("zed", Path(".rules"), MANAGED_BLOCK),
    "cody": Target("cody", Path(".cody/rules/vaultwares.md"), MANAGED_BLOCK),
    "jb": Target("jb", Path(".idea/aiassistant/context.md"), MANAGED_BLOCK),
}



def replace_or_append(existing: str, block: str) -> str:
    if START_MARKER in existing and END_MARKER in existing:
        start = existing.index(START_MARKER)
        end = existing.index(END_MARKER) + len(END_MARKER)
        return (existing[:start] + block.strip() + existing[end:]).rstrip() + "\n"

    if not existing.strip():
        return block.strip() + "\n"

    return existing.rstrip() + "\n\n" + block.strip() + "\n"


def resolve_targets(names: Iterable[str]) -> list[Target]:
    selected = list(names)
    if not selected or "all" in selected:
        selected = list(TARGETS)

    unknown = [name for name in selected if name not in TARGETS]
    if unknown:
        allowed = ", ".join(["all", *sorted(TARGETS)])
        raise SystemExit(f"Unknown target(s): {', '.join(unknown)}. Allowed: {allowed}")

    deduped: list[Target] = []
    seen_paths: set[Path] = set()
    for name in selected:
        target = TARGETS[name]
        if target.relative_path not in seen_paths:
            deduped.append(target)
            seen_paths.add(target.relative_path)
    return deduped


def ensure_consumer_root(consumer_root: Path, submodule_path: str) -> None:
    if not consumer_root.exists():
        raise SystemExit(f"Consumer root does not exist: {consumer_root}")

    vault_themes = consumer_root / submodule_path
    if not vault_themes.exists():
        raise SystemExit(
            f"Consumer repo does not appear to contain a vault-themes submodule: {vault_themes}"
        )


def sync_target(consumer_root: Path, target: Target, *, check: bool, dry_run: bool) -> bool:
    path = consumer_root / target.relative_path
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    seed = existing
    if not seed.strip() and target.empty_prefix:
        seed = target.empty_prefix.rstrip() + "\n\n"

    updated = replace_or_append(seed, target.block)

    changed = existing != updated
    if check:
        status = "ok" if not changed else "needs update"
        print(f"{status}: {path}")
        return changed

    if dry_run:
        action = "would update" if changed else "unchanged"
        print(f"{action}: {path}")
        return changed

    if changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(updated, encoding="utf-8")
        print(f"updated: {path}")
    else:
        print(f"unchanged: {path}")

    return changed


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync vault-themes submodule guidance into consumer repo agent and IDE files."
    )
    parser.add_argument("consumer_root", help="Absolute or relative path to the consumer repository root.")
    parser.add_argument(
        "--targets",
        nargs="+",
        default=["codex", "claude", "copilot", "cursor"],
        help="Targets to sync. Use 'all' for every supported surface.",
    )
    parser.add_argument(
        "--submodule-path",
        default="vault-themes",
        help="Path to the vault-themes submodule relative to the consumer root.",
    )
    parser.add_argument("--check", action="store_true", help="Report whether files need updates and exit non-zero if they do.")
    parser.add_argument("--dry-run", action="store_true", help="Show planned updates without writing files.")
    parser.add_argument("--write", action="store_true", help="Write updates. This is the default unless --check or --dry-run is set.")
    args = parser.parse_args()

    consumer_root = Path(args.consumer_root).resolve()
    ensure_consumer_root(consumer_root, args.submodule_path)

    targets = resolve_targets(args.targets)
    changed = False
    for target in targets:
        changed = sync_target(consumer_root, target, check=args.check, dry_run=args.dry_run) or changed

    return 1 if args.check and changed else 0


if __name__ == "__main__":
    raise SystemExit(main())
